---
- hosts: localhost
  gather_facts: false
  vars:
    k8s_kubeconfig: ~/.kube/eks-example
    k8s_no_log: true

  tasks:
    - name: Deploy Jenkins.
      k8s:
        definition: '{{ item }}'
        kubeconfig: '{{ k8s_kubeconfig }}'
        state: present
      loop:
        - "{{ lookup('template', 'jenkins-service.yml') | from_yaml_all | list }}"
        - "{{ lookup('template', 'sonarqube.yml') | from_yaml_all | list }}"
