---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: default
  labels:
    app: sonarqube
    type: devops
spec:
  selector:
    app: sonarqube
    type: devops
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-deployment
  namespace: default
  labels:
    app: sonarqube
    type: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
      type: devops
  template:
    metadata:
      labels:
        app: sonarqube
        type: devops
    spec:
      containers:
      - name: sonarqube
        image: sonarqube
        ports:
        - containerPort: 9000
        