---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: default
  labels:
    app: jenkins
    type: devops
spec:
  selector:
    app: jenkins
    type: devops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: default
  labels:
    app: jenkins
    type: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      type: devops
  template:
    metadata:
      labels:
        app: jenkins
        type: devops
    spec:
      containers:
      - name: jenkins
        image: 2121994/jenkins-docker
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-home
          emptyDir: {}